### ISSUE TITLE
Promisfied version

### ISSUE THREAD

**Issue by berstend** [ecmadao/chrome-utils#1]
Hey there, thanks for chrome-utils! I must agree that the `chrome.storage` API is pretty anti-human 😄.

I'm a sucker for `async/await` so I made a quick promisfying wrapper for `store`:

```js
// chrome-utils-promise.js
// Promifies: https://github.com/ecmadao/chrome-utils
import { store } from 'chrome-utils';

const storePromisfied = {
  get: function(key) {
    return new Promise(resolve => {
      store.get(key, resolve)
    })
  },
  set: function(key, value, options = {}) {
    return new Promise(resolve => {
      store.set(key, value, { callback: e => resolve(e) })
    })
  },
  clear: function() {
    return new Promise(resolve => {
      store.clear(e => resolve(e))
    })
  },
  remove: function(key) {
    return new Promise(resolve => {
      store.remove(key, e => resolve(e))
    })
  },
}

export {
  storePromisfied as store
}
```

Usage:
```js
import { store } from './chrome-utils-promise';

// with promises
store.set('a', "xxx").then(e => console.log("done"))
store.get('a').then(e => console.log(e))
store.remove('a').then(e => console.log("done"))
store.clear().then(e => console.log("done"))

// with async/await
(async function() {
    await store.set("b", "yyy")
    const b = await store.get("b")
    console.debug("b", b)
})()
```

This is too tiny to warrant it's on repo or npm release, so I'm just leaving this here for others (and my future self 😄).  

Thanks again!

**Comment by ecmadao** [comment]
Cool! I think the promise version is more helpful and user-friendly. And maybe you can create a PR to merge your version? Thanks! @berstend

**Comment by berstend** [comment]
@ecmadao what do you think is the best way here, add another export so the user could do `import { storePromise } from 'chrome-utils';` or to replace the callback versions entirely?

**Comment by ecmadao** [comment]
@berstend 
I think maybe adding a new `storePromise` api is more friendly for this module's user, so I'll give it a vote.
